version: '3.7'
services:
    redis:
        image: 'redis:5.0.5-alpine'
        deploy:
            replicas: 1
    flask-service:
        build:
            context: ./flask-service
            dockerfile: Dockerfile
        depends_on:
            - "redis"
        ports:
            - '8080:8080'
        volumes:
            - './flask-service:/app'
            - './common-data:/data'
    worker-service_1:
        build:
            context: ./worker-service
            dockerfile: Dockerfile
        depends_on:
            - "redis"
        volumes:
            - './worker-service:/app'
            - './common-data:/data'
    worker-service_2:
        build:
            context: ./worker-service
            dockerfile: Dockerfile
        depends_on:
            - "redis"
        volumes:
            - './worker-service:/app'
            - './common-data:/data'
    test_environment:
        build:
            context: ./tests
            dockerfile: Dockerfile
        volumes:
            - './tests:/app'
            - './test-data:/data'
        stdin_open: true
        tty: true
